
package com.emc.security;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WeblogicSecurityService", targetNamespace = "http://Security.emc.com/", wsdlLocation = "http://127.0.0.1:7001/WeblogicSecurity/WeblogicSecurityService?WSDL")
public class WeblogicSecurityService
    extends Service
{

    private final static URL WEBLOGICSECURITYSERVICE_WSDL_LOCATION;
    private final static WebServiceException WEBLOGICSECURITYSERVICE_EXCEPTION;
    private final static QName WEBLOGICSECURITYSERVICE_QNAME = new QName("http://Security.emc.com/", "WeblogicSecurityService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1:7001/WeblogicSecurity/WeblogicSecurityService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBLOGICSECURITYSERVICE_WSDL_LOCATION = url;
        WEBLOGICSECURITYSERVICE_EXCEPTION = e;
    }

    public WeblogicSecurityService() {
        super(__getWsdlLocation(), WEBLOGICSECURITYSERVICE_QNAME);
    }

    public WeblogicSecurityService(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBLOGICSECURITYSERVICE_QNAME, features);
    }

    public WeblogicSecurityService(URL wsdlLocation) {
        super(wsdlLocation, WEBLOGICSECURITYSERVICE_QNAME);
    }

    public WeblogicSecurityService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBLOGICSECURITYSERVICE_QNAME, features);
    }

    public WeblogicSecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WeblogicSecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WeblogicSecurity
     */
    @WebEndpoint(name = "WeblogicSecurityPort")
    public WeblogicSecurity getWeblogicSecurityPort() {
        return super.getPort(new QName("http://Security.emc.com/", "WeblogicSecurityPort"), WeblogicSecurity.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WeblogicSecurity
     */
    @WebEndpoint(name = "WeblogicSecurityPort")
    public WeblogicSecurity getWeblogicSecurityPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Security.emc.com/", "WeblogicSecurityPort"), WeblogicSecurity.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBLOGICSECURITYSERVICE_EXCEPTION!= null) {
            throw WEBLOGICSECURITYSERVICE_EXCEPTION;
        }
        return WEBLOGICSECURITYSERVICE_WSDL_LOCATION;
    }

}
