
package com.systemlogic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WeblogicSecurity", targetNamespace = "http://Security.emc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WeblogicSecurity {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHai", targetNamespace = "http://Security.emc.com/", className = "com.systemlogic.SayHai")
    @ResponseWrapper(localName = "sayHaiResponse", targetNamespace = "http://Security.emc.com/", className = "com.systemlogic.SayHaiResponse")
    public String sayHai(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
